### ISSUE TITLE
docker-compose run app bin/run throwing error

### ISSUE THREAD

**Issue by rustsol** [heycarsten/labici-magento-shopify-migrator#1]
D:\www\migrate3>docker-compose run app bin/run
Starting migrate3_db_1 ... done
Traceback (most recent call last):
        4: from bin/run:3:in `<main>'
        3: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        2: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        1: from /labici/lib/labici.rb:14:in `<top (required)>'
/labici/lib/labici.rb:14:in `require': /labici/lib/labici/customer_activator.rb:9: syntax error, unexpected tFID, expecting ')' (SyntaxError)
      init_db!
      ^~~~~~~~

**Comment by dean224** [comment]
@yogisfunda I have the same problem. Have you solved it?

**Comment by gpinkham** [comment]
open the lib/labici/customer_activiator.rb file and add a `)` to the end of line 8..   so it should look like this: 
```
      @db = Sequel.sqlite(File.join(root, 'data/customers.db'))
```

**Comment by dwrf6** [comment]
@gpinkham I've updated the file, 👍
